# Generated by Django 3.1.6 on 2022-05-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, default='<DJANGO.DB.MODELS.FIELDS.CHARFIELD><DJANGO.DB.MODELS.FIELDS.TEXTFIELD>'),
        ),
    ]
