# Generated by Django 3.1.6 on 2022-05-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220523_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, default='<BOUND METHOD FIELD.VALUE_TO_STRING OF <DJANGO.DB.MODELS.FIELDS.CHARFIELD>><BOUND METHOD FIELD.VALUE_TO_STRING OF <DJANGO.DB.MODELS.FIELDS.TEXTFIELD>>'),
        ),
    ]
