# Generated by Django 3.1.6 on 2022-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220523_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
