# Generated by Django 3.1.6 on 2022-05-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220523_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
    ]
